---
# PolyMorph Calamares Configuration (Version 1: Arch Linux)
sequence:
  show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - netinstall
    - summary
  exec:
    - partition
    - mount
    - unpackfs
    - networkcfg
    - hwclock
    - machineid
    - fstab
    - locale
    - keyboard
    - localenc
    - packages
    - grubcfg
    - bootloader
    - umount
  show:
    - finished

modules-search: [./modules]
branding: polymorph

welcome:
  showSupportUrl: false
  showKnownIssuesUrl: false
  showReleaseNotesUrl: false

netinstall:
  url: file:///etc/calamares/netinstall.yaml

packages:
  removeUnselected: false

bootloader:
  efiBootLoader: "grub"
  biosBootLoader: "grub"
